env_path = ["~/.local/bin", "~/bin"]

[env]
EDITOR = 'lvim'
GIT_SSH = 'ssh'
PIP_REQUIRE_VIRTUALENV = 'true'
PYTHONBREAKPOINT = 'ipdb.set_trace'
PYTHON_CFLAGS = '-march=native -mtune=native'
PYTHON_CONFIGURE_OPTS = '--enable-shared --enable-optimizations --with-lto --enable-loadable-sqlite-extensions'

[tools]
argocd = '2.7.2'
duf = 'latest'
fd = 'latest'
fzf = '0.40.0'
github-cli = '2.29.0'
helm = 'latest'
jq = '1.6'
kustomize = '5.0.3'
lua-language-server = 'latest'
kubectl = 'latest'
minikube = 'latest'
shellcheck = '0.9.0'
shfmt = 'latest'
stylua = 'latest'
yamlfmt = 'latest'
yarn = 'latest'
terraform = "1.3"
deno = 'latest'
rust = 'stable'
node = ["latest", "20", "18", "16"]
go = ["latest", "1.20", "1.19", "1.18"]
python = ["3.11", "3.10", "3.9", "3.8"]

[settings]
experimental = true
