env_path = ["~/.local/bin", "~/bin"]

[env]
EDITOR = 'lvim'
GIT_SSH = 'ssh'
PIP_REQUIRE_VIRTUALENV = 'true'

[tools]
argocd = '2.7.2'
duf = 'latest'
fd = 'latest'
fzf = '0.40.0'
github-cli = '2.29.0'
helm = 'latest'
jq = '1.6'
kustomize = 'latest'
lua-language-server = 'latest'
minikube = 'latest'
shellcheck = '0.9.0'
shfmt = 'latest'
stylua = 'latest'
terraform = 'latest'
deno = 'latest'
rust = 'stable'
node = ["latest", "20", "18", "16"]
golang = ["latest", "1.20", "1.19", "1.18"]
python = "3.11"

[settings]
experimental = true
