---
# TODO: Fix this step (arch)
- name: Install gcloud required packages
  become_user: root
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: latest
- name: Add gcloud public key to usr share keyrings
  become_user: root
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
    state: present
- name: Add gcloud repo to apt sources list
  become_user: root
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
    filename: google-cloud-sdk.list
    update_cache: yes
    state: present
- name: Install google-cloud-cli with apt
  become_user: root
  apt:
    pkg:
      - google-cloud-cli
    update_cache: yes
