---
- name: "Install golang"
  become_user: root
  apt:
    pkg:
      - golang
    state: latest
- name: "Install golang kubernetes libs"
  shell: |
    go get -u github.com/derailed/k9s
    GO111MODULE=on go install golang.stackrox.io/kube-linter/cmd/kube-linter
    go get -u github.com/hidetatz/kubecolor/cmd/kubecolor
- name: "Install golang libs"
  shell: |
    go get -u github.com/jesseduffield/lazydocker
    go get -u github.com/sachaos/tcpterm
