---
- name: "Install golang"
  become_user: root
  apt:
    pkg:
      - golang
    state: latest
- name: "Install golang libs"
  shell: |
    go get github.com/jesseduffield/lazydocker
    go get github.com/derailed/k9s
    go get github.com/sachaos/tcpterm
