---
- name: Check for nvm installation
  stat: path=~/.nvm/nvm.sh
  register: nvm
- name: Make nvm build script executable
  become: true
  become_user: "{{user}}"
  become_method: sudo
  shell: >
    chmod +x ~/dotfiles/tasks/files/build/nvm.sh
- name: "Install nvm"
  shell: >
    curl -ssL -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
  when: not nvm.stat.exists
- name: Install node
  script:
    cmd: ~/dotfiles/tasks/files/build/nvm.sh
