---
- name: Check for nvm installation
  stat: path=~/.nvm/nvm.sh
  register: nvm
- name: "Install nvm"
  shell: >
    curl -ssL -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
  when: not nvm.stat.exists
- name: Install node
  script:
    cmd: ~/dotfiles/tasks/files/build/nvm.sh
