---
- name: "Update system packages"
  become_user: root
  apt:
    pkg:
      - libtool-bin
      - libpcap-dev
      - htop
      - cargo
      - bat
      - tree
      - ncdu
      - curl
      - fonts-powerline
      - build-essential
      - redis
      - redis-server
      - fzf
      - flatpak
      - sed
      - g++
      - tmux
    state: latest
    autoremove: yes
    autoclean: yes
- name: "Create local dir"
  file:
    path: ~/.local/bin
    state: directory
- name: "Create local build dir"
  file:
    path: ~/.local_build
    state: directory
- name: "Update flatpak packages"
  become_user: root
  shell: |
    flatpak update
    flatpak uninstall --unused
- name: "Install btop"
  become_user: root
  shell: |
    wget -qO /tmp/btop.tbz https://github.com/aristocratos/btop/releases/latest/download/btop-x86_64-linux-musl.tbz
    sudo tar xf /tmp/btop.tbz -C /usr/local bin/btop
    btop --version
    rm -rf /tmp/btop.tbz
# - name: "Install sysz"
#   shell: |
#     wget -qO ~/bin/sysz https://github.com/joehillen/sysz/releases/latest/download/sysz
#     sudo chmod +x ~/bin/sysz
- name: "Install kmon required packages"
  become_user: root
  apt:
    pkg:
      - libxcb1-dev
      - libxcb-shape0-dev
      - libxcb-xfixes0-dev
      - libxcb-render0-dev
# - name: "Install kmon through cargo"
#  command: cargo install kmon
