---
- name: Check for poetry installation
  stat: path=~/.poetry/bin/poetry
  register: poetry
- name: "Install poetry"
  become_user: root
  shell: >
    curl -sSL -o- https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -
  when: not poetry.stat.exists
