---
- name: "Check for poetry installation"
  stat: path=~/.poetry/bin/poetry
  register: poetry
- name: "Install poetry"
  become_user: root
  command: "curl -sSL -o- https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 - "
  when: not poetry.stat.exists
- name: "Config poetry"
  shell: |
    poetry config virtualenvs.create true
    poetry config virtualenvs.in-project true
  when: not poetry.stat.exists
- name: "Update poetry version"
  command: "poetry self update"
