---
- name: Check for pyenv installation
  stat: path=~/.pyenv
  register: pyenv
- name: "Install pyenv"
  shell: curl https://pyenv.run | bash
  when: not pyenv.stat.exists
- name: "Install python3 pip"
  become_user: root
  apt:
    pkg:
      - python3-pip
    state: latest
- name: Set pip require virtualenv to false
  become_user: root
  shell: |
    PIP_REQUIRE_VIRTUALENV=false
- name: Install python packages
  become_user: root
  command: "pip install --user {{ item }}"
  with_items:
    - black
    - cmake
    - codespell
    - debugpy
    - flake8
    - ipython
    - isort
    - numpy
    - pandas
    - pip
    - pre-commit
    - pynvim
    - wheel
    - yamllint
