DOTFILES_FILES_DIR="$HOME/dotfiles/files"
OS=$(source $DOTFILES_FILES_DIR/scripts/get_os.sh)
SETTINGS_FILE="$DOTFILES_FILES_DIR/config/bash/rc_$OS.sh"
[[ -s $SETTINGS_FILE ]] && source $SETTINGS_FILE

# oh-my-zsh config
export ZSH_WAKATIME_PROJECT_DETECTION=true
CASE_SENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"
DISABLE_VENV_CD=1

# antigen
source "$HOME/.antigen.zsh"
antigen use oh-my-zsh
antigen bundle colored-man-pages
antigen bundle colorize
antigen bundle common-aliases
antigen bundle docker
antigen bundle encode64
antigen bundle extract
antigen bundle fzf
antigen bundle gitfast
antigen bundle npm
antigen bundle systemd
antigen bundle git
# github
antigen bundle zdharma-continuum/fast-syntax-highlighting
antigen bundle jocelynmallon/zshmarks
antigen bundle wbingli/zsh-wakatime
antigen bundle popstas/zsh-command-time
# theme
antigen theme agnoster
antigen apply
autoload -U +X compinit && compinit

# alias
alias gdff="git difftool --dir-diff"
alias c="clear"
alias tf="terraform "

# kube-ps1 
KUBE_PS1_SH="$HOME/.local_build/kube-ps1/kube-ps1.sh"
if [ -f $KUBE_PS1_SH ]; then 
  source $KUBE_PS1_SH
  kubeon
  PROMPT='$(kube_ps1)'$PROMPT
fi
