FROM sickcodes/docker-osx:latest

RUN mkdir -p /dotfiles
WORKDIR /dotfiles

RUN apt-get update && apt-get install -y \
  make \
  ansible \
  vim \
  sudo

COPY ./../tasks tasks
COPY ./../macos.yml macos.yml
COPY ./../files.yml files.yml
COPY ./..//Makefile Makefile
COPY ./../settings.sh settings.sh
COPY ./../run_ansible.sh run_ansible.sh
