command_timeout = 1000

format = """
$directory\
$git_branch\
$git_state\
$git_metrics\
$fill\
$python\
$golang\
$terraform\
$cmd_duration\
$jobs\
$line_break\
$character"""

right_format = """
$aws\
$azure\
$gcloud\
$kubernetes\
$time"""

[aws]
disabled = false

[azure]
disabled = true

[gcloud]
disabled = true

[character]
success_symbol = '[>](bold green)'
error_symbol = '[>](bold red)'
vimcmd_symbol = '[<](bold green)'

[fill]
symbol = ' '

[git_metrics]
disabled = false

[time]
disabled = false

[kubernetes]
disabled = false
detect_env_vars = ['STARSHIP_K8S']
