---
- name: Install node packages
  become: true
  become_method: sudo
  become_user: "{{user}}"
  shell: source ~/.nvm/nvm.sh && npm -g i {{item}} --force
  args:
    executable: /bin/bash
  with_items:
    - corepack
    - ts-node
    - typescript
    - yarn
    - eslint
    - graphql
    - prettier
    - neoss
