DOTFILES_DIR="$HOME/dotfiles"
GET_OS_SCRIPT="$DOTFILES_DIR/scripts/utils/get_os.sh"
RTX_BIN="${HOME}/.local/share/rtx/bin/rtx"
P10K_CONFIG="$DOTFILES_DIR/config/zsh/p10k.zsh"
ANTIGEN_PATHS=(
  "$HOME/antigen.zsh"
  "$HOME/.antigen.zsh"
)
ZSHRC_CORE="$DOTFILES_DIR/config/zsh/.zshrc_core.sh"
[[ -s $ZSHRC_CORE ]] && source $ZSHRC_CORE

# Load bashrc and antigen safely
load_bashrc
for ANTIGEN_PATH in "${ANTIGEN_PATHS[@]}"; do
  if [ -s "$ANTIGEN_PATH" ]; then
    ant_path="$ANTIGEN_PATH"
    break
  fi
done
if [[ -z $ant_path ]]; then
  echo "Error: Could not find antigen in any of: ${ANTIGEN_PATHS[*]}"
  return 1
fi
source $ant_path

# oh-my-zsh config
export ZSH_WAKATIME_PROJECT_DETECTION=true
CASE_SENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"
DISABLE_VENV_CD=1

antigen use oh-my-zsh
antigen bundle colored-man-pages
antigen bundle colorize
antigen bundle common-aliases
antigen bundle encode64
antigen bundle extract
antigen bundle fzf
antigen bundle gitfast
antigen bundle kubectl
antigen bundle kubectx
antigen bundle npm
antigen bundle pip
antigen bundle python
antigen bundle systemd
antigen bundle git
antigen bundle yarn
# github
antigen bundle sheax0r/etcdctl-zsh
antigen bundle gantsign/zsh-plugins kubeadm
antigen bundle sunlei/zsh-ssh
antigen bundle zdharma-continuum/fast-syntax-highlighting
antigen bundle jocelynmallon/zshmarks
antigen bundle wbingli/zsh-wakatime
antigen bundle popstas/zsh-command-time
# theme
antigen theme romkatv/powerlevel10k
antigen apply
autoload -U +X compinit && compinit

# alias
alias c="clear"
alias tf="terraform "
alias lg="lazygit"
alias nvim="lvim "

# p10k settings
[[ ! -f ${P10K_CONFIG} ]] || source ${P10K_CONFIG}
[[ ! -f "${RTX_BIN}"  ]] || eval "$(${RTX_BIN} activate -s zsh)"
