---
- name: Add an apt signing key for kubernetes
  become_user: root
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: Adding apt repository for kubernetes
  become_user: root
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list
- name: Install kubernetes binaries
  become_user: root
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubectl
    state: present
- name: Restart kubelet
  become_user: root
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted
