---
- name: Install required apt packages for gvm
  become_user: root
  apt:
    pkg:
      - curl
      - bison
      - mercurial
      - make
      - binutils
      - gcc
      - build-essential
- name: "Check if GVM is installed"
  stat: path=~/.gvm/bin/gvm
  register: gvm
- name: Install golang version manager (GVM)
  become: true
  become_method: sudo
  become_user: "{{user}}"
  shell: |
    curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer | bash
  when: not gvm.stat.exists
- name: Make gvm build script executable
  become: true
  become_user: "{{user}}"
  become_method: sudo
  shell: >
    chmod +x ~/dotfiles/files/build/gvm.sh
- name: Install golang
  script:
    cmd: ~/dotfiles/files/build/gvm.sh
- name: "Install golang libs"
  shell: |
    source ~/.gvm/scripts/gvm
    go install golang.stackrox.io/kube-linter/cmd/kube-linter@latest
    go install github.com/ipinfo/cli/ipinfo@latest
    go install github.com/jesseduffield/lazygit@latest
    go install github.com/jesseduffield/lazydocker@latest
    go install github.com/sachaos/tcpterm@latest
    go install github.com/instrumenta/kubeval@latest
    go install github.com/mikefarah/yq/v4@latest
    go install github.com/stern/stern@latest
    go install github.com/controlplaneio/kubesec/v2@latest
  args:
    executable: /bin/bash
