
source "$HOME/.antigen.zsh"
source ~/.nvm/nvm.sh

if [ -f "$HOME/bootstrap/entrypoint.sh" ]; then
  source "$HOME/bootstrap/entrypoint.sh"
fi

# oh-my-zsh config
CASE_SENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"
DISABLE_VENV_CD=1

antigen use oh-my-zsh

# oh-my-zsh
antigen bundle common-aliases
antigen bundle docker
antigen bundle encode64
antigen bundle extract
antigen bundle fzf
antigen bundle gitfast
antigen bundle npm
antigen bundle systemd

# theme
antigen theme agnoster

antigen apply

autoload -U compinit && compinit