source "$HOME/.antigen.zsh"

SETTINGS_FILE="$HOME/dotfiles/settings.sh"

if [ -f $SETTINGS_FILE ]; then
  source $SETTINGS_FILE
fi

export ZSH_WAKATIME_PROJECT_DETECTION=true

# oh-my-zsh config
CASE_SENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
HIST_STAMPS="yyyy-mm-dd"
DISABLE_VENV_CD=1

antigen use oh-my-zsh

# oh-my-zsh
antigen bundle colored-man-pages
antigen bundle colorize
antigen bundle common-aliases
antigen bundle docker
antigen bundle encode64
antigen bundle extract
antigen bundle fzf
antigen bundle gitfast
antigen bundle npm
antigen bundle systemd
antigen bundle git

# github
antigen bundle zdharma-continuum/fast-syntax-highlighting
antigen bundle jocelynmallon/zshmarks
antigen bundle wbingli/zsh-wakatime
antigen bundle popstas/zsh-command-time

# theme
antigen theme agnoster

antigen apply

autoload -U +X compinit && compinit

# alias
alias gdff="git difftool --dir-diff"
alias c="clear"
alias tf="terraform "

# kube-ps1 
if [ -f $KUBE_PS1_SH ]; then 
  source $KUBE_PS1_SH
  kubeoff
  PROMPT='$(kube_ps1)'$PROMPT
fi
