[settings]
experimental = true

[env]
_.path = ["~/.local/bin", "~/bin"]
EDITOR = 'lvim'
GIT_SSH = 'ssh'
PERL_LOCAL_LIB_ROOT = '{{env.HOME}}/.local/perl'
PIP_REQUIRE_VIRTUALENV = 'true'
PYTHONBREAKPOINT = 'ipdb.set_trace'
RIPGREP_CONFIG_PATH = '{{env.HOME}}/dotfiles/config/rg/ripgreprc'
PYTHON_CFLAGS = '-march=native -mtune=native'
PYTHON_CONFIGURE_OPTS = '--enable-shared --enable-optimizations --with-lto --enable-loadable-sqlite-extensions'

[tools]
# tools
actionlint = 'latest'
argocd = 'latest'
awscli = 'latest'
cloud-sql-proxy = 'latest'
cmctl = 'latest'
doctl = 'latest'
duf = 'latest'
fd = 'latest'
fzf = 'latest'
jq = 'latest'
gcloud = 'latest'
github-cli = 'latest'
gomplate = 'latest'
helm = 'latest'
helm-diff = 'latest'
helm-docs = 'latest'

# Kubernetes tools
kubesec = 'latest'
kubent = 'latest'
kube-score = 'latest'
kubectl = ["latest", "1.27", "1.26"]
kubecolor = "latest"
kubectx = 'latest'
kubeseal = 'latest'
kustomize = 'latest'
k9s = 'latest'
k3d = '4.4.8'
velero = 'latest'

lazygit = 'latest'
lua-language-server = 'latest'
kind = "latest"
pdm = 'latest'
pre-commit = 'latest'
ripgrep = 'latest'
stern = 'latest'
shellcheck = 'latest'
shfmt = 'latest'
stylua = 'latest'
trivy = 'latest'
terraform = ["latest", "1.5", "1.3"]
terraform-docs = 'latest'
terraform-ls = 'latest'
terraformer = "latest"
terragrunt = 'latest'
teleport-community = ["15.1.4", "11.3.6"]
yamlfmt = 'latest'
yq = 'latest'

# npm tools
"npm:@astrojs/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:cloc" = "latest"
"npm:cspell" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:eslint_d" = "latest"
"npm:fixjson" = "latest"
"npm:graphql" = "latest"
"npm:graphql-language-service-cli" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:opencollective" = "latest"
"npm:patch-package" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:stylelint" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:ts-server" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"

# Languages
deno = 'latest'
rust = 'stable'
node = ["latest", "20", "18", "16"]
go = ["latest", "1.20", "1.19", "1.18"]
python = ["3.12", "3.11"]
java = ["adoptopenjdk-11.0.21+9"]
