[env]
OPENCODE_EXPERIMENTAL_ICON_DISCOVERY = "true"
OPENCODE_EXPERIMENTAL_FILEWATCHER = "true"
OPENCODE_EXPERIMENTAL_LSP_TOOL = "true"
CLAUDE_CONFIG_DIR = "{{env.HOME}}/.claude"
CLAUDE_CODE_NO_FLICKER = "1"

[tools]
opencode = "latest"
"cargo:tuicr" = 'latest'
"cargo:https://github.com/rtk-ai/rtk" = "latest"
