[settings]
experimental = true
cache_prune_age = "7d"
locked = true
idiomatic_version_file_enable_tools = [
    "python",
    "node",
    "go",
    "terraform",
    "terragrunt",
    "opentofu",
]

[settings.pipx]
uvx = true

[settings.python]
uv_venv_auto = true

[settings.npm]
bun = true

[tools]
# Languages
bun = 'latest'
deno = 'latest'
go = ['latest', '1.20', '1.19', '1.18']
node = ['latest', '20', '18', '16']
python = ['latest', '3.13', '3.12', '3.11']
rust = '1.92.0'

# CLI tools
actionlint = 'latest'
argocd = 'latest'
ast-grep = 'latest'
aws-cli = 'latest'
aws-sso = 'latest'
biome = 'latest'
bottom = 'latest'
cheat = 'latest'
cmctl = 'latest'
delta = 'latest'
duf = 'latest'
fd = 'latest'
fzf = 'latest'
jq = 'latest'
github-cli = 'latest'
groovy = 'latest'
gomplate = 'latest'
helm = 'latest'
helm-diff = 'latest'
helm-docs = 'latest'
"aqua:mrjosh/helm-ls" = 'latest'

# Kubernetes tools
kubesec = 'latest'
kubent = 'latest'
kube-score = 'latest'
kubectl = ['1.32']
kubecolor = 'latest'
kubectx = 'latest'
kubeseal = 'latest'
kustomize = 'latest'
k9s = 'latest'
k3d = 'latest'
kind = 'latest'
velero = 'latest'

lua-language-server = 'latest'
marksman = 'latest'
pdm = 'latest'
pnpm = 'latest'
poetry = 'latest'
pre-commit = 'latest'
ripgrep = 'latest'
ruff = 'latest'
rust-analyzer = 'latest'
starship = 'latest'
stern = 'latest'
shfmt = 'latest'
stylua = 'latest'
trivy = 'latest'
opentofu = 'latest'
terraform = ['latest']
terraform-docs = 'latest'
"aqua:hashicorp/terraform-ls" = 'latest'
"aqua:terraform-linters/tflint" = 'latest'
terraformer = 'latest'
terragrunt = 'latest'
yazi = 'latest'
yamlfmt = 'latest'
yamllint = 'latest'
yq = 'latest'

# pipx tools
"pipx:autotools-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:codespell" = "latest"
"pipx:django-language-server" = "latest"
"pipx:djlint" = "latest"
"pipx:ipython" = "latest"
"pipx:mypy" = "latest"
"pipx:nox" = "latest"
"pipx:pyrefly" = "latest"
"pipx:pytest" = "latest"
"pipx:pytest-language-server" = "latest"
"pipx:python-lsp-server" = { version = "latest", extras = "all" }
"pipx:tox" = "latest"
"pipx:ty" = "latest"

# npm tools
"npm:@astrojs/language-server" = "latest"
"npm:@github/copilot" = "latest"
"npm:@github/copilot-language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:cloc" = "latest"
"npm:cspell" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:eslint_d" = "latest"
"npm:fixjson" = "latest"
"npm:gh-actions-language-server" = "latest"
"npm:lua-3p-language-servers" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:mermaid-cli" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:stylelint" = "latest"
"npm:ts-server" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"

# cargo tools
'cargo:cargo-update' = 'latest'
'cargo:gctx' = 'latest'
'cargo:grip-grab' = 'latest'
'cargo:taplo-cli' = 'latest'
'cargo:tree-sitter-cli' = 'latest'

# go tools
'go:github.com/incu6us/goimports-reviser/v3' = 'latest'
'go:github.com/kkk777-7/ingress2eg' = 'latest'
'go:github.com/kubernetes-sigs/ingress2gateway' = 'v1.0.0'
'go:github.com/segmentio/golines' = 'latest'
'go:golang.org/x/tools/gopls' = 'latest'
'go:mvdan.cc/gofumpt' = 'latest'
