env_path = ["~/.local/bin", "~/bin"]

[env]
EDITOR = 'lvim'
GIT_SSH = 'ssh'
PERL_LOCAL_LIB_ROOT = '{{env.HOME}}/.local/perl'
PIP_REQUIRE_VIRTUALENV = 'true'
PYTHONBREAKPOINT = 'ipdb.set_trace'
PYTHON_CFLAGS = '-march=native -mtune=native'
PYTHON_CONFIGURE_OPTS = '--enable-shared --enable-optimizations --with-lto --enable-loadable-sqlite-extensions'
RIPGREP_CONFIG_PATH = '{{env.HOME}}/dotfiles/config/rg/ripgreprc'

[tools]
# tools
actionlint = 'latest'
argocd = 'latest'
awscli = 'latest'
cloud-sql-proxy = 'latest'
doctl = 'latest'
duf = 'latest'
fd = 'latest'
fzf = 'latest'
gcloud = 'latest'
github-cli = 'latest'
helm = 'latest'
helm-diff = 'latest'

kubesec = 'latest'
kubent = 'latest'
kube-score = 'latest'
kubectl = ["latest", "1.27", "1.26"]
kubecolor = "latest"
kubectx = 'latest'
kubeseal = 'latest'
kustomize = 'latest'
k9s = 'latest'

lazygit = 'latest'
lua-language-server = 'latest'
kind = "latest"
pdm = 'latest'
pre-commit = 'latest'
ripgrep = 'latest'
stern = 'latest'
shellcheck = 'latest'
shfmt = 'latest'
stylua = 'latest'
terraform = ["latest", "1.5", "1.3"]
terraform-ls = "latest"
terraformer = "latest"
yamlfmt = 'latest'
yq = 'latest'

# Languages
deno = 'latest'
rust = 'stable'
node = ["latest", "20", "18", "16"]
go = ["latest", "1.20", "1.19", "1.18"]
python = ["3.12", "3.11"]
