[settings]
experimental = true

[env]
_.path = ["~/.local/bin", "~/bin"]
EDITOR = 'nvim'
GIT_SSH = 'ssh'
PERL_LOCAL_LIB_ROOT = '{{env.HOME}}/.local/perl'
PIP_REQUIRE_VIRTUALENV = 'true'
RIPGREP_CONFIG_PATH = '{{env.HOME}}/dotfiles/config/rg/ripgreprc'
# python build settings
PYTHON_CFLAGS = '-march=native -mtune=native'
PYTHON_CONFIGURE_OPTS = '--enable-shared --enable-optimizations --with-lto --enable-loadable-sqlite-extensions'

[tools]
# tools
actionlint = 'latest'
argocd = 'latest'
awscli = 'latest'
cloud-sql-proxy = 'latest'
cmctl = 'latest'
doctl = 'latest'
duf = 'latest'
fd = 'latest'
fzf = 'latest'
jq = 'latest'
gcloud = 'latest'
github-cli = 'latest'
gomplate = 'latest'
helm = 'latest'
helm-diff = 'latest'
helm-docs = 'latest'

# Kubernetes tools
kubesec = 'latest'
kubent = 'latest'
kube-score = 'latest'
kubectl = ["latest", "1.27", "1.26"]
kubecolor = "latest"
kubectx = 'latest'
kubeseal = 'latest'
kustomize = 'latest'
k9s = 'latest'
k3d = '4.4.8'
velero = 'latest'

lazygit = 'latest'
lua-language-server = 'latest'
kind = "latest"
pdm = 'latest'
pre-commit = 'latest'
ripgrep = 'latest'
stern = 'latest'
shellcheck = 'latest'
shfmt = 'latest'
stylua = 'latest'
trivy = 'latest'
opentofu = "1.6.2"
terraform = ["latest", "1.5", "1.3"]
terraform-docs = 'latest'
terraform-ls = 'latest'
terraformer = "latest"
terragrunt = "0.57.2"
teleport-community = "15.1.4"
yamlfmt = 'latest'
yq = 'latest'

# npm tools
"npm:@astrojs/language-server" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:bash-language-server" = "latest"
"npm:cloc" = "latest"
"npm:cspell" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:eslint" = "latest"
"npm:eslint_d" = "latest"
"npm:fixjson" = "latest"
"npm:graphql" = "latest"
"npm:graphql-language-service-cli" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:opencollective" = "latest"
"npm:patch-package" = "latest"
"npm:pnpm" = "latest"
"npm:prettier" = "latest"
"npm:pyright" = "latest"
"npm:stylelint" = "latest"
"npm:tree-sitter-cli" = "latest"
"npm:ts-server" = "latest"
"npm:typescript" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
# pipx tools
"pipx:basedpyright" = "latest"
"pipx:black" = "latest"
"pipx:codespell" = "latest"
"pipx:djlint" = "latest"
"pipx:flake8" = "latest"
"pipx:ipython" = "latest"
"pipx:isort" = "latest"
"pipx:mypy" = "latest"
"pipx:pdm" = "latest"
"pipx:pipx" = "latest"
"pipx:poetry" = "latest"
"pipx:ruff" = "latest"
"pipx:tox" = "latest"
"pipx:yamlfix" = "latest"
"pipx:yamllint" = "latest"

# langs
deno = 'latest'
go = ["latest", "1.20", "1.19", "1.18"]
node = ["latest", "20", "18", "16"]
python = ['latest', 'sub-0.1:latest', 'sub-0.2:latest', 'sub-0.3:latest', 'sub-0.4:latest']
rust = 'latest'
