[settings.npm]
bun = true

[tools]
bun = 'latest'
cloud-sql-proxy = 'latest'
doctl = 'latest'
gcloud = 'latest'

# npm tools
"npm:graphql" = "latest"
"npm:graphql-language-service-cli" = "latest"
"npm:opencollective" = "latest"
